minuta 1
unamfi/CarTheftBot pull request #7
Opened 2017-08-02 15:18 UTC by devCharles

la primer minuta del proyecto, me la envió Alberto Ladron para hacerla pública
esta nuestro sprint 0 para empezar a trabajar

2017-08-02 15:55 UTC, juanpflores commented
Hey @devCharles! 👋 
LGTM voy a unir tu PR

2017-08-02 15:58 UTC, juanpflores approved these changes

2017-08-02 16:01 UTC, juanpflores commented
@JuIioCesar 

- [ ] Revisa los cambios
- [ ] Agrega Comentarios si se necesita.
- [ ] Squash de los commits
- [ ] Merge del PR
- [ ] Borrar la rama

Please 👍

2017-08-02 22:43 UTC, juliofruta requested changes
Por favor revisen mis comentarios.

2017-08-02 22:43 UTC, JuIioCesar commented on minutas/minuta1-2017-8-02.md
> +* Julio Fruta - iOS Developer
Estoy repetido aqui.

2017-08-02 22:43 UTC, JuIioCesar commented on minutas/minuta1-2017-8-02.md
> +# Historias - Sprint 0
¿Podemos pasar esto al project?

2017-08-02 22:43 UTC, JuIioCesar commented on minutas/minuta1-2017-8-02.md
> +* Julio Fruta - iOS Developer
Estoy repetido

2017-08-02 22:43 UTC, JuIioCesar commented on minutas/minuta1-2017-8-02.md
> +# (Car Theft) Minuta de reunion
Esto es lo mismo que tenemos en el sheet de Google Docs. ¿es necesario llevarlo? ¿No es mejor solamente actualizar el Google Docs? No soy muy fan de subir minutas a Github. Me parece sobre-documentarlo.

2017-08-03 15:06 UTC, devCharles commented
Hoy creare el tablero de trello creo que si seria mejor llevarlo todo ahí y no subir minutas a gh, esta idea originalmente era de Alberto pero lo hablaré con el

2017-08-05 07:41 UTC, JuIioCesar commented
@devCharles Para eso esta el project. No necesitamos trello.

2017-08-05 07:42 UTC, JuIioCesar commented
https://github.com/unamfi/CarTheftBot/projects/1

2017-08-14 05:45 UTC, closed without merging